### ISSUE TITLE
Snapshot Sync

### ISSUE THREAD

**Issue by avichalp** [OpenFarcaster/teleport#9]
As mentioned [here](https://github.com/OpenFarcaster/teleport/issues/8), the Hub must index the required EVM events before it can listen to or send Farcaster messages. The indexing job may take a couple of hours to sync before you could start the Hub. 

One way to mitigate this issue is to download the snapshots made available by existing Hubs and use them instead of downloading data from the blockchain. Here is how you can download these snapshots from S3:

1) Get the S3 key for the latest snapshot by calling this API: https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_7/latest.json
2) Download the actual snapshot from: https://download.farcaster.xyz/

Step 2 gives a compressed rocks db dump. We must decompress and restore it into a local rocks db instance. Finally, we want to extract all the data from Rocks db and store it in Teleport's local SQLite.

This is essentially how [Replicator](https://github.com/farcasterxyz/hub-monorepo/tree/main/apps/replicator) works. It reads the data from the hub and stores it in a Postgres DB. A good start would be to figure out the structure of rocks db as it is used in [Hubble](https://github.com/farcasterxyz/hub-monorepo/tree/main/apps/hubble). Identify all the different key spaces and how they translate to teleport [schema](https://github.com/OpenFarcaster/teleport/blob/main/lib/storage/migrations/20231118180138_farcaster.sql).

**Comment by haardikk21** [comment]
So we have two options, really

If we look at ETH Node snapshot syncs for example - there are different clients which have vastly different underltying data structures

Option #1 obviously is to build a compatible pipeline for Hubble and sync snapshots they produce

But, Option #2 also exists where we have our own snapshots that are independent of Hubble

Will need to take a look into how big of a task it is to actually become compatible with Hubble snapshots

**Comment by avichalp** [comment]
> Will need to take a look into how big of a task it is to actually become compatible with Hubble snapshots

It doesn't sound like it would be straightforward! It is essentially like writing our Replicator pipeline. However, it can be an async and independent project. It doesn't block us from implementing other features in Teleport to achieve feature/spec parity with Hubble.

**Comment by gregfromstl** [comment]
Personally in favor of Option 2 (avoids reliance on Hubble for anything which makes Teleport a greater asset to the network overall)

**Comment by haardikk21** [comment]
At this point, a snapshot sync for teleport simply requires downloading and copy-pasting `farcaster.db` and `state.json`. Can we close this?
